apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: weather-pipeline-run-4
spec:
  serviceAccountName: weather-svc
  pipelineRef:
    name: weather-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: weather-git
    - name: weather-image
      resourceRef:
        name: weather-image
